[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
console = "0.16.0"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
rusqlite = "0.37.0"
